/*Desafio: alterando informações*/
UPDATE [TABELA DE VENDEDORES] SET [PERCENTUAL COMISSÃO] = 0.11 WHERE (MATRICULA = 00235)
UPDATE [TABELA DE VENDEDORES] SET NOME = 'Cláudia Morais Sousa' WHERE (MATRICULA = 00236)