/*Desafio: datas e campos lógicos*/

/*Criação da Tabela*/
CREATE TABLE [TABELA DE VENDEDORES](
	MATRICULA VARCHAR(5) NOT NULL,
	NOME VARCHAR(100) NULL,
	CIDADE VARCHAR(100) NULL,
	[PERCENTUAL COMISSÃO] FLOAT NOT NULL,
	[DATA INICIO] DATE NOT NULL,
	TEM_DEPENDENTE BIT);

/*Adicionando chave primária*/
ALTER TABLE [TABELA DE VENDEDORES] ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED (MATRICULA);

/*Incluindo Vendedor*/
INSERT INTO [TABELA DE VENDEDORES]
VALUES
(00239, 'Alberto de Sá Verneck', 'São Paulo', 0.08, '2020-06-05', 1);

/*Visualizar tabela*/
SELECT * FROM [TABELA DE VENDEDORES]